// Copyright (c) 2026 Reza Rahimi / Softside Tech Pty Ltd. All rights reserved.
// SPDX-License-Identifier: MPL-2.0

//! Raw FFI bindings to Fraunhofer FDK AAC v2.0.3.
//!
//! This crate provides unsafe bindings generated by bindgen. Use `aac-audio`
//! for the safe wrapper.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decoder_open_close_smoke() {
        unsafe {
            let handle = aacDecoder_Open(TRANSPORT_TYPE_TT_MP4_RAW, 1);
            assert!(!handle.is_null(), "aacDecoder_Open returned null");
            aacDecoder_Close(handle);
        }
    }

    #[test]
    fn encoder_open_close_smoke() {
        unsafe {
            let mut handle: HANDLE_AACENCODER = std::ptr::null_mut();
            let err = aacEncOpen(&mut handle, 0, 2);
            assert_eq!(err, AACENC_ERROR_AACENC_OK, "aacEncOpen failed: {err:?}");
            assert!(!handle.is_null());
            let err = aacEncClose(&mut handle);
            assert_eq!(
                err,
                AACENC_ERROR_AACENC_OK,
                "aacEncClose failed: {err:?}"
            );
        }
    }
}
